#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorGeneratorTest.Views.Test
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RazorGeneratorTest;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Test/Standard.cshtml")]
    public partial class Standard : System.Web.Mvc.WebViewPage<string>
    {
        public Standard()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

  
	Layout = null;

WriteLiteral("\r\n\r\n<div");

WriteAttribute("style", Tuple.Create(" style=\"", 126), Tuple.Create("\"", 159)
, Tuple.Create(Tuple.Create("", 134), Tuple.Create("background-color:", 134), true)
, Tuple.Create(Tuple.Create(" ", 151), Tuple.Create<System.Object, System.Int32>(Model
, 152), false)
, Tuple.Create(Tuple.Create("", 158), Tuple.Create(";", 158), true)
);

WriteLiteral(">Work!</div>\r\n");

        }
    }
}
#pragma warning restore 1591
